### PR TITLE
Use primary key and and proper data types in DB schema

### PR DESCRIPTION
**Pull request by addstar**
This makes changes the table schema in the DB:
- Makes the `UUID` field a primary key, so it's impossible to have duplicates.
- Use more appropriate data types (char/varchar) to better suit the data in the table.

Currently untested because I'm unable to build the plugin due to missing dependencies.

This won't properly fix the issue, it will just prevent the duplicates, but will cause SQL exception errors. The real fix to this is to change the logic inside `PlayerJoinEvent` and `loadStatistic` so that all statistics are loaded in a single SQL query/task. The duplicate insertion is happening because of concurrent tasks checking/inserting records independently.

If I can get the project to build properly, I'll restructure the stat loading to work that way.

### CODE REVIEW

**Comment by Plajer** [comment]
??????

**Comment by Plajer** [comment]
idk missclick

**Comment by addstar** [comment]
I'm not sure about cracked servers, I don't had anything to do with them, but I checked the code and it only stores `player.getName()` (not `displayName`). So it can only ever be a real Minecraft name, which has a max of 16 chars. Can make it longer for safety if you like?

**Comment by Plajer** [comment]
yes

**Comment by addstar** [comment]
I'm closing this - Instead of these small changes, I'm redoing the DB handling to fix the duplicate records and make statistic loading more efficient.. larger PR coming soon

**Pull request closed without merging**
